---
- name: Instala MySQL
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - python3-pymysql
    - mysql-server
    - mysql-client
    - libmysqlclient-dev

- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql.password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql.password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql.password }}"